version: '3.8'

services:
  db-service:
    build: .
    ports:
      - "6001:6001"
    environment:
      - NODE_ENV=production
      - PORT=6001
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - kb-network

networks:
  kb-network:
    driver: bridge