version: '3.8'

services:
  university-service:
    build: .
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=production
      - PORT=7000
      - DB_SERVICE_URL=http://db-service:6001
    depends_on:
      - db-service
    networks:
      - university-network

  db-service:
    build: ./db-service
    ports:
      - "6001:6001"
    environment:
      - NODE_ENV=production
      - PORT=6001
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - university-network

networks:
  university-network:
    driver: bridge